version: '2.1'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./LDC.Atlas.sln && dotnet publish ./LDC.Atlas.sln -c Release -o ./obj/Docker/publish"
